import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/utils/provider'
import '@/styles/globals.scss'
import Nav from '@/components/nav/Nav'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '선사주',
  description: 'Generated by create next app',
}

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <html lang="ko">
    <body className={inter.className}>
      <Nav />
      <Providers>{children}</Providers>
      <Footer />
    </body>
  </html>
)
export default RootLayout
