import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/utils/provider'
import '@/styles/globals.scss'
import TopNavbar from '@/components/nav/TopNavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        {/* <TopNavbar /> */}
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
